# Apply selected filter mode to entire bitmap
#' Title
#'
#' @param bitmap A 3D raw array (dimensions 3 × height × width) representing the RGB values of the image. Usually generated by \code{read_image_as_bitmap()}.
#' @param mode A string specifying the filter type to apply. Options: "greyscale", "red", "green", "blue", or "cutoff".
#' @param cutoff Integer between 0 and 255 used only when \code{mode = "cutoff"}; defaults to 127.
#'
#' @return A 3D raw array representing the filtered image bitmap.
#' @export new_bitmap

apply_filter_to_bitmap <- function(bitmap, mode = "greyscale", cutoff = 127) {
  dim_data <- dim(bitmap)
  new_bitmap <- bitmap

  for (y in 1:dim_data[2]) {
    for (x in 1:dim_data[3]) {
      rgb_raw <- bitmap[1:3, y, x]
      new_color <- filter_rgb(rgb_raw, mode, cutoff)
      new_bitmap[1:3, y, x] <- new_color
    }
  }

  return(new_bitmap)
}
